# Generated by Django 3.0.3 on 2020-02-16 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=150, verbose_name='Название игры')),
                ('product_text', models.TextField(verbose_name='О товаре')),
                ('product_image', models.ImageField(upload_to=None)),
                ('product_price', models.IntegerField()),
                ('pub_date', models.DateTimeField(verbose_name='Дата публикации')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
