# Generated by Django 3.0.3 on 2020-03-21 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0004_auto_20200321_1045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 21, 11, 35, 15, 610462), verbose_name='Дата публикации'),
        ),
    ]
